// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_API_Controladores_3.Models;

#nullable disable

namespace Web_API_Controladores_3.Migrations
{
    [DbContext(typeof(MyDBcontext))]
    [Migration("20240913062313_Migracion_De_Inicio")]
    partial class Migracion_De_Inicio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Web_API_Controladores_3.Models.Empleado", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpleado"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdRolEnEmpleado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salaraio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdEmpleado");

                    b.HasIndex("IdRolEnEmpleado");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("Web_API_Controladores_3.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Web_API_Controladores_3.Models.Empleado", b =>
                {
                    b.HasOne("Web_API_Controladores_3.Models.Rol", "Objeto_Rol")
                        .WithMany("Lista_Empleados")
                        .HasForeignKey("IdRolEnEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Objeto_Rol");
                });

            modelBuilder.Entity("Web_API_Controladores_3.Models.Rol", b =>
                {
                    b.Navigation("Lista_Empleados");
                });
#pragma warning restore 612, 618
        }
    }
}
